version: '3.8'

services:
  web-app:
    image: nginx:alpine
    container_name: portafolio-web-app
    ports:
      - "80:80"
    volumes:
      - ./portafolio-web:/usr/share/nginx/html:ro
      - ./nginx-app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge